### ISSUE TITLE
"NoneType object is not subscriptable

### ISSUE THREAD

**Issue by SgtSobieski** [Memessidy/protonmail_generator#5]
Hi there,

the following error occures, which seem to be because of a minor error, because it comes when account has generally been created and you are asked to enter your username. Tried it with both first mail accounts, but I think that doesnt matter as those are working finde.

Would be nice if you could check on that.:

`
Trying to create account...
Message: 
Stacktrace:
#0 0x5565e6f21303 <unknown>
#1 0x5565e6c062b7 <unknown>
#2 0x5565e6c51cc0 <unknown>
#3 0x5565e6c51db1 <unknown>
#4 0x5565e6c95b44 <unknown>
#5 0x5565e6c743ad <unknown>
#6 0x5565e6c9307c <unknown>
#7 0x5565e6c74123 <unknown>
#8 0x5565e6c44095 <unknown>
#9 0x5565e6c4509e <unknown>
#10 0x5565e6ee56ab <unknown>
#11 0x5565e6ee94ba <unknown>
#12 0x5565e6ed1f85 <unknown>
#13 0x5565e6eea12f <unknown>
#14 0x5565e6eb5e6f <unknown>
#15 0x5565e6f0e5f8 <unknown>
#16 0x5565e6f0e7c2 <unknown>
#17 0x5565e6f204a4 <unknown>
#18 0x7fbeae094ac3 <unknown>

Bad try! Stopping current...
'NoneType' object is not subscriptable
No accounts((
`

**Comment by Memessidy** [comment]
Hi! Please try to download repo and try again, I think I had fixed

**Comment by Memessidy** [comment]
> Hi! Please try to download repo and try again, I think I had fixed

Hi! Please try to download repo and try again, I think I had fixed

**Comment by Memessidy** [comment]
> Hi there,
> 
> the following error occures, which seem to be because of a minor error, because it comes when account has generally been created and you are asked to enter your username. Tried it with both first mail accounts, but I think that doesnt matter as those are working finde.
> 
> Would be nice if you could check on that.:
> 
> ` Trying to create account... Message: Stacktrace: #0 0x5565e6f21303 #1 0x5565e6c062b7 #2 0x5565e6c51cc0 #3 0x5565e6c51db1 #4 0x5565e6c95b44 #5 0x5565e6c743ad #6 0x5565e6c9307c #7 0x5565e6c74123 #8 0x5565e6c44095 #9 0x5565e6c4509e #10 0x5565e6ee56ab #11 0x5565e6ee94ba #12 0x5565e6ed1f85 #13 0x5565e6eea12f #14 0x5565e6eb5e6f #15 0x5565e6f0e5f8 #16 0x5565e6f0e7c2 #17 0x5565e6f204a4 #18 0x7fbeae094ac3
> 
> Bad try! Stopping current... 'NoneType' object is not subscriptable No accounts(( `

Hi! Please try to download repo and try again, I think I had fixed

**Comment by SgtSobieski** [comment]
Works again. Nice work - thanks!
